// @hidden
import { useCallback, useEffect, useRef, useState } from "react";

interface ScrollState {
  isAtBottom: boolean;
  autoScrollEnabled: boolean;
}

interface UseAutoScrollOptions {
  offset?: number;
  smooth?: boolean;
  content?: React.ReactNode;
}

export function useAutoScroll(options: UseAutoScrollOptions = {}) {
  const { offset = 20, smooth = false, content } = options;
  const scrollRef = useRef<HTMLDivElement>(null);
  const lastContentHeight = useRef(0);
  const userHasScrolled = useRef(false);
  const autoScrollEnabledRef = useRef(true);

  const [scrollState, setScrollState] = useState<ScrollState>({
    isAtBottom: true,
    autoScrollEnabled: true,
  });

  const checkIsAtBottom = useCallback(
    (element: HTMLElement) => {
      const { scrollTop, scrollHeight, clientHeight } = element;
      const distanceToBottom = Math.abs(
        scrollHeight - scrollTop - clientHeight
      );
      return distanceToBottom <= offset;
    },
    [offset]
  );

  const scrollToBottom = useCallback(
    (instant?: boolean) => {
      if (!scrollRef.current) return;

      const targetScrollTop =
        scrollRef.current.scrollHeight - scrollRef.current.clientHeight;

      if (instant) {
        scrollRef.current.scrollTop = targetScrollTop;
      } else {
        scrollRef.current.scrollTo({
          top: targetScrollTop,
          behavior: smooth ? "smooth" : "auto",
        });
      }

      autoScrollEnabledRef.current = true;
      setScrollState((prev) =>
        prev.isAtBottom && prev.autoScrollEnabled
          ? prev
          : {
              isAtBottom: true,
              autoScrollEnabled: true,
            }
      );
      // The setter returns the previous object when already at bottom, so
      // scroll events generated by streaming cannot cause same-state rerenders.
      userHasScrolled.current = false;
    },
    [smooth]
  );

  const handleScroll = useCallback(() => {
    if (!scrollRef.current) return;

    const atBottom = checkIsAtBottom(scrollRef.current);

    setScrollState((prev) => {
      const nextAutoScrollEnabled = atBottom ? true : prev.autoScrollEnabled;
      autoScrollEnabledRef.current = nextAutoScrollEnabled;
      if (
        prev.isAtBottom === atBottom &&
        prev.autoScrollEnabled === nextAutoScrollEnabled
      ) {
        return prev;
      }
      return {
        isAtBottom: atBottom,
        // Re-enable auto-scroll if at the bottom
        autoScrollEnabled: nextAutoScrollEnabled,
      };
    });
  }, [checkIsAtBottom]);

  useEffect(() => {
    const element = scrollRef.current;
    if (!element) return;

    element.addEventListener("scroll", handleScroll, { passive: true });
    return () => element.removeEventListener("scroll", handleScroll);
  }, [handleScroll]);

  useEffect(() => {
    const scrollElement = scrollRef.current;
    if (!scrollElement) return;

    const currentHeight = scrollElement.scrollHeight;
    const hasNewContent = currentHeight !== lastContentHeight.current;

    if (hasNewContent) {
      if (autoScrollEnabledRef.current) {
        requestAnimationFrame(() => {
          scrollToBottom(lastContentHeight.current === 0);
        });
      }
      lastContentHeight.current = currentHeight;
    }
    // Streaming mutates content frequently, so this effect reads auto-scroll state
    // from a ref and depends only on content plus the stable scroll callback.
  }, [content, scrollToBottom]);

  useEffect(() => {
    const element = scrollRef.current;
    if (!element) return;

    const resizeObserver = new ResizeObserver(() => {
      if (autoScrollEnabledRef.current) {
        scrollToBottom(true);
      }
    });

    resizeObserver.observe(element);
    // ResizeObserver callbacks use a ref for auto-scroll state to avoid rebuilding
    // the observer after every scrollState write during streamed responses.
    return () => resizeObserver.disconnect();
  }, [scrollToBottom]);

  const disableAutoScroll = useCallback(() => {
    const atBottom = scrollRef.current
      ? checkIsAtBottom(scrollRef.current)
      : false;

    // Only disable if not at bottom
    if (!atBottom) {
      userHasScrolled.current = true;
      autoScrollEnabledRef.current = false;
      setScrollState((prev) =>
        prev.autoScrollEnabled ? { ...prev, autoScrollEnabled: false } : prev
      );
    }
  }, [checkIsAtBottom]);

  return {
    scrollRef,
    isAtBottom: scrollState.isAtBottom,
    autoScrollEnabled: scrollState.autoScrollEnabled,
    scrollToBottom: () => scrollToBottom(false),
    disableAutoScroll,
  };
}
